// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBg9FNYJmwkn_5Tvpe-PCT45pGk2aGsUY',
    appId: '1:47780300743:web:b7c78866a2f14e88477be2',
    messagingSenderId: '47780300743',
    projectId: 'codeapp-6ea06',
    authDomain: 'codeapp-6ea06.firebaseapp.com',
    storageBucket: 'codeapp-6ea06.appspot.com',
    measurementId: 'G-90PB8YMJ9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3xVzgaWoM0hXWf1HQ3TPxLHBxT0b3n0',
    appId: '1:47780300743:android:dca00fa5e88f7c2c477be2',
    messagingSenderId: '47780300743',
    projectId: 'codeapp-6ea06',
    storageBucket: 'codeapp-6ea06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJzwKke7cDZ5xV7j4nGzrZ24q6BoMeG1w',
    appId: '1:47780300743:ios:ddd914f27d48fed1477be2',
    messagingSenderId: '47780300743',
    projectId: 'codeapp-6ea06',
    storageBucket: 'codeapp-6ea06.appspot.com',
    iosBundleId: 'com.example.techmobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJzwKke7cDZ5xV7j4nGzrZ24q6BoMeG1w',
    appId: '1:47780300743:ios:ddd914f27d48fed1477be2',
    messagingSenderId: '47780300743',
    projectId: 'codeapp-6ea06',
    storageBucket: 'codeapp-6ea06.appspot.com',
    iosBundleId: 'com.example.techmobapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBg9FNYJmwkn_5Tvpe-PCT45pGk2aGsUY',
    appId: '1:47780300743:web:c06f1d6777233654477be2',
    messagingSenderId: '47780300743',
    projectId: 'codeapp-6ea06',
    authDomain: 'codeapp-6ea06.firebaseapp.com',
    storageBucket: 'codeapp-6ea06.appspot.com',
    measurementId: 'G-87Q2ZKSFKW',
  );
}
